### ISSUE TITLE
what is this app?

### ISSUE THREAD

**Issue by ret394** [Staacks/phyphox-android#13]
found on froid. shows 1 hour from starting download to still not "installing" -> https://github.com/Staacks/phyphox-android

how to cancel?
please nuke this or mark as experimental in Readme or description.

**Comment by ret394** [comment]
reboot it. and now its gone. don't use app, solved.

f-droid sucks, just provide apk, cut the appstore crap.

**Comment by Staacks** [comment]
Your first comment should probably go to F-Droids bug tracker (although this sounds like a dodgy connection or an overloaded server).

But I gladly explain why there is no apk for phyphox as this explanation might be interesting for others searching for this.

The short answer is: We do not provide an apk, because we want to encourage sources that allow for automated updated. One aspect is that you should always keep your software up to date for security reasons (this is not only because of errors in the code of apps but also libraries and frameworks used by these apps).

The other more practical aspect for us is that phyphox is designed to be used in class and we want to make sure that teachers can expect the same behavior, the same features and sometimes the same problems on all devices. This does not only apply to classes in school. We use phyphox in a 300+ course at our University and cannot deal with individual cases in which a function is not available because phyphox has been installed two years ago from an apk that has never been updated.

Of course we cannot prevent users from disabling updates or simply installing the apk from F-Droid, but directly offering an apk on our website would encourage students to pick this one, leading to inconsistent versions across classes.

For those who are searching for an apk and who are tenacious enough to read up to here: You can directly download apks for every version from F-Droids website. This is the only source for an apk that we consider secure (except for some local school clouds)! As we do not distribute apks, all other websites that directly provide apks have taken them without asking and without a concept to keep them up-to-date. While phyphox is free and open source, this is less a legal matter than a matter of good practice. (I understand that people have privacy concerns when using Google services and we support F-Droid because of this, but I would not trust a site that simply scrapes software from other sources.)
