### ISSUE TITLE
applyZoom requires expanding and collapsing other graphs before taking effect

### ISSUE THREAD

**Issue by scspaeth** [Staacks/phyphox-android#4]
On Android Beta, the expanded view of a graph allows to adjust pan and zoom. The expanded view offers advanced options to "keep as selected" and apply to other graphs. If one selects 'Other graphs: Same axis', and hits 'OK', I expected other graphs to display the intended changes. They did not. The changes are only invoked when each of the other graphs are individually expanded. 
https://github.com/Staacks/phyphox-android/blob/14bcf50d45fa1a7368f0660fc2060935d5780364/app/src/main/java/de/rwth_aachen/phyphox/expView.java#L1663

**Comment by Staacks** [comment]
This is strange, I cannot reproduce it on my phone. Is this specific to a certain experiment or does it happen in all experiments? Does this happen regardless of whether the experiment is still running or only when the experiment is stopped? Which phone and (probably more important) Android version are you using?

**Comment by scspaeth** [comment]
It is not specific to a certain experiment. 
I had not tried to make the change while the experiment was running. At your suggestion, I tested while an experiment was running. It works as intended for that case but reverts to the buggy case when the experiment is stopped. 
I am using a G pad F 8.0 Tablet
It is running Android version 6.0

**Comment by Staacks** [comment]
ok, this makes sense and seems to be a simple issue of needing to force a refresh. Curiously, this is no problem on an Android 8 and Android 9 device I tested, even when the measurement is stopped, but I was able to reproduce the problem on an Android 4 device. Introducing a simple refresh-request fixed it on this device and the fix is just in time to be in the official 1.1.0 release on Monday (17th June 2019).

Please feel free to open (or comment on) this issue again if the problem still persists with the (non-beta) release on Monday.

**Comment by scspaeth** [comment]
Looking forward to the release on Monday! Thank you.
